fileHandle = open("myFile.txt", "r")
line = fileHandle.readline()
print(line)
line = fileHandle.readline()
print(line)
line = fileHandle.readline()
print(line)
line = fileHandle.readline()
print(line)
fileHandle.close()